export const GET_RECENT = 'GET_RECENT';
export const SEARCH_PHOTO = 'SEARCH_PHOTO';
export const HANDLE_SEARCH_TERM_CHANGE = 'ON_SEARCH_TYPE';
export const HANDLE_SEARCH_TERM_SUBMIT = 'ON_SEARCH_SUBMIT';
export const GOOGLE_SIGNIN = 'GOOGLE_SIGNIN';
export const GOOGLE_SIGNOUT = 'GOOGLE_SIGNOUT';